services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    env_file:
      - ../account/.env
    restart: unless-stopped
